### ISSUE TITLE
push access

### ISSUE THREAD

**Issue by pixelass** [esdoc2/esdoc2-plugins#13]
Hi. can you please give me push access so I can prepare a few PRs? I don't want to keep a mirrored version in my private profile unless strictly needed.

**Comment by MattMcFarland** [comment]
Yes

On Mar 12, 2018 7:51 AM, "Gregor Adams" <notifications@github.com> wrote:

Hi. can you please give me push access so I can prepare a few PRs? I don't
want to keep a mirrored version in my private profile unless strictly
needed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/esdoc2/esdoc2-plugins/issues/13>, or mute the thread

**Comment by MattMcFarland** [comment]
Push access given
